[package]
name = "wallet-cli"
version = "0.1.1"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"

[[bin]]
name = "wallet"
path = "src/main.rs"

[dependencies]
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", branch = "develop", features = ["sqlite"] }
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
tokio = { version = "0.2", features = ["full"] }
dialoguer = "0.7"
console = "0.13"
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
once_cell = "1.4"
serde_json = "1.0"
futures = "0.3"
tiny-bip39 = "0.7"
dotenv = "0.15"

[profile.release]
lto = true
codegen-units = 1

[patch.crates-io]
paho-mqtt = { git = "https://github.com/rajivshah3/paho.mqtt.rust", branch = "feature/openssl-static-link-master"}
