[package]
name = "stardust-cli-wallet"
version = "0.1.0-alpha"
authors = [ "IOTA Stiftung" ]
edition = "2021"
homepage = "https://iota.org"
description = "Command line interface application for the IOTA wallet library."
license = "Apache-2.0"

[[bin]]
name = "wallet"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.6", features = [ "derive" ] }
dialoguer = "0.10.0"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "62e554445db31c2183370eded892b44556bb8af3" }
prefix-hex = { version = "0.4.0", default-features = false, features = [ "std" ] }
tokio = { version = "1.12.0", default-features = false }

# serde_json = { version = "1.0.68", default-features = false }
# futures = "0.3.17"
# notify-rust = "4.5.6"

[profile.release]
lto = true
codegen-units = 1
