[package]
name = "stardust-cli-wallet"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://iota.org"
description = "Command line interface application for the IOTA wallet library."
license = "Apache-2.0"

[[bin]]
name = "wallet"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "bbc2cebbf179c3497404eb43cf5cd88a0d00560b" }
# iota-wallet = { path = "../wallet.rs" }
tokio = { version = "1.12.0", default-features = false }
dialoguer = "0.10.0"
clap = { version = "3.1.6", features = ["derive"] }
# serde_json = { version = "1.0.68", default-features = false }
# futures = "0.3.17"
# notify-rust = "4.5.6"
# TODO remove when the crypto/bee version mismatch is fixed
iota-crypto = { version = "0.9.2", default-features = false, features = ["std", "random", "sha", "pbkdf", "hmac", "bip39", "bip39-en", "chacha", "blake2b", "slip10"] }

[profile.release]
lto = true
codegen-units = 1
