[package]
name = "wallet-cli"
version = "0.5.3"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://iota.org"
description = "Command line interface application for the IOTA wallet library."
license = "Apache-2.0"

[[bin]]
name = "wallet"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "3621db720237c864042c72f9879127c8b017526c" }
# iota-wallet = { path = "../wallet.rs" }
tokio = { version = "1.12.0", default-features = false }
dialoguer = "0.8.0"
clap = "3.1.6"
serde_json = { version = "1.0.68", default-features = false }
futures = "0.3.17"
notify-rust = "4.5.6"

[profile.release]
lto = true
codegen-units = 1
