[package]
name = "wallet-cli"
version = "0.3.6"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"
homepage = "https://iota.org"
description = "Command line interface application for the IOTA wallet library."
license = "Apache-2.0"

[[bin]]
name = "wallet"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", branch = "develop", features = ["ledger-nano", "ledger-nano-simulator"] }
iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "be869fc47117f996cf040c8466ba4023d70cacfa" }
tokio = { version = "1.1", features = ["full"] }
dialoguer = "0.7"
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
once_cell = "1.4"
serde_json = "1.0"
futures = "0.3"

[patch.crates-io]
paho-mqtt = { git = "https://github.com/rajivshah3/paho.mqtt.rust", branch = "feature/openssl-static-link-master-0.9"}

[profile.release]
lto = true
codegen-units = 1
