[package]
name = "wallet-cli"
version = "0.4.1"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"
homepage = "https://iota.org"
description = "Command line interface application for the IOTA wallet library."
license = "Apache-2.0"

[[bin]]
name = "wallet"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", branch = "develop", features = ["ledger-nano", "ledger-nano-simulator"] }
iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "f837a9df7c0f3cecbff87eb6ac3d458d1e50dee0" }
tokio = { version = "1.1", features = ["full"] }
dialoguer = "0.8"
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
serde_json = "1.0"
futures = "0.3"
notify-rust = "4"

[profile.release]
lto = true
codegen-units = 1
